### ISSUE TITLE
Google Drive link does not work

### ISSUE THREAD

**Issue by amir-ghz** [bbussolino/Q-CapsNets#2]
Hi, great work! Your code is very clean and highly readable. The only thing is that the google drive link for the pre-trained weights does not exist and google threw the error: "Sorry, the file you have requested does not exist."

I appreciate it if you could fix the link.

**Comment by bbussolino** [comment]
Should be fixed, can you confirm?

**Comment by amir-ghz** [comment]
Yes, works just fine! Thank you.
